name: Android CI

on: [push]

create_property_files:
  stage: prepare
  only:
    - master
  script:
    - echo $KEYSTORE_FILE | base64 -d > my.keystore
    - echo "keystorePath=my.keystore" > keystore.properties
    - echo "keystorePassword=$KEYSTORE_PASSWORD" >> keystore.properties
    - echo "keyAlias=$ALIAS" >> keystore.properties
    - echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
  artifacts:
    paths:
      - my.keystore
      - keystore.properties
    expire_in: 10 mins

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      uses: create_property_files
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
