name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_CONFIG: ${{ secrets.GOOGLE_SERVICES_CONFIG }}
        run: echo $GOOGLE_SERVICES_CONFIG > app/google-services.json
      - name: Echo release keystore
        env:
          APP_KEYSTORE: ${{ secrets.APP_KEYSTORE }}
        run: echo $APP_KEYSTORE
      - name: Decode release keystore
        env:
          APP_KEYSTORE: ${{ secrets.APP_KEYSTORE }}
        run: echo $APP_KEYSTORE | base64 -di > app/simpleinc.jks
      - name: Build with Gradle
        env:
          RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
          RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
          RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
        run: ./gradlew build

